- name: delete sca pipeline
  hosts: sca-dev
  gather_facts: false
  serial: 1
  vars:
    provider: "{{ hostvars[inventory_hostname]['provider'] }}"
    vault: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/vault.yml"
  tasks:
    # - name: revoke licenses
    #   bigip_command:
    #     commands: revoke sys license
    #     provider:
    #       server: "{{item.host}}"
    #       password: secret
    #       user: admin
    #   delegate_to: localhost
    - name: delete sca pipeline
      cloudformation:
        stack_name: "{{provider.aws.cf.pipeline.name}}"
        state: "absent"
        region: "{{awsRegion}}"
      delegate_to: localhost