- name: create sca stack
  hosts: sca-dev
  gather_facts: false
  serial: 1
  vars:
    provider: "{{ hostvars[inventory_hostname]['provider'] }}"
    vault: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/vault.yml"
  tasks:
    - name: create sca stack
      cloudformation:
        stack_name: "{{provider.name}}"
        state: "present"
        region: "{{awsRegion}}"
        disable_rollback: true
        template: "f5-sca-securitystack/aws-quickstart-scca-main-same-net.json"
        template_parameters:
          licenseKey1: "{{provider.license.bigip1}}"
          licenseKey2: "{{provider.license.bigip2}}"
          licenseKey3: "{{provider.license.bigip3}}"
          licenseKey4: "{{provider.license.bigip4}}"
          pBaselineCompliance: "{{provider.compliance}}"
          pProject: "quickstart-f5-scca-security"
          pQuickstartS3BucketName: "{{provider.aws.s3.bucket.name}}"
          pQuickstartS3KeyPrefix: "{{provider.aws.s3.bucket.folder}}"
          pVdssVpcCidr: "{{provider.cidr}}"
          sshKey: "{{provider.aws.ec2.sshkeyname}}"
        tags:
          Stack: "ansible-sca-cloudformation"
      delegate_to: localhost