- name: create sca pipeline
  hosts: sca-dev
  gather_facts: false
  serial: 1
  vars:
    sca: "{{ hostvars[inventory_hostname]['sca'] }}"
    vault: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/vault.yml"
  tasks:
    - name: create sca pipeline
      cloudformation:
        stack_name: "{{sca.aws.cf.pipeline.name}}"
        state: "present"
        region: "{{awsRegion}}"
        disable_rollback: true
        #template: "f5-sca-securitystack/aws-quickstart-scca-main-same-net.json"
        template_url: "{{sca.aws.cf.pipeline.url}}"
        capabilities: ["CAPABILITY_AUTO_EXPAND","CAPABILITY_IAM","CAPABILITY_NAMED_IAM"]
        template_parameters:
          BranchName: "{{sca.aws.s3.bucket.folder}}"
          GitHubOwner: "vinnie357"
          OAuthSecretName: "sca-git-pipeline"
          RepositoryName: "f5-sca-securitystack"
          S3Bucket: "{{sca.aws.s3.bucket.name}}"
          S3Key: "{{sca.aws.s3.bucket.folder}}"
        tags:
          Stack: "ansible-sca-cloudformation"
      delegate_to: localhost