# branches
# work-mazza-tmsh-updates
# master
sca:
  name: "mazza-sca-dev"
  compliance: "SCCA"
  git:
    #owner: "mikeoleary"
    owner: "vinnie357"
    #branch: "master"
    branch: "mazza-fargate-juice-shop"
  aws:
    vpc:
      vdss:
        cidr: "10.0.0.0/16"
      app:
        cidr: "10.1.0.0/16"
      fargate:
        cidr: "10.2.0.0/16" 
    s3:
      bucket: 
        name: "f5-sca-mazza"
        # name: "f5-sca-securitystack"
        # folder: "master"
        folder: "mazza-fargate-juice-shop"
    ec2:
      sshkeyname: "mazza-aws"
      tier1Size: "c4.xlarge"
      tier2Size: "c4.2xlarge"
    cf:
      template:
        url: "https://f5-sca-mazza.s3.amazonaws.com/mazza-fargate-juice-shop/aws-quickstart-scca-main-same-net.json"
        # url: https://f5-sca-securitystack.s3.amazonaws.com/master/aws-quickstart-scca-main-same-net.json
      pipeline:
        url: "https://f5-sca-securitystack.s3.amazonaws.com/master/deploy-pipeline.template"
        name: "sca-git-pipeline-master"
  license:
    bigip1: "{{ vault_license.bigip1 }}"
    bigip2: "{{ vault_license.bigip2 }}"
    bigip3: "{{ vault_license.bigip3 }}"
    bigip4: "{{ vault_license.bigip4 }}"
  