- name: delete sca pipeline aws
  hosts: sca_aws
  gather_facts: false
  serial: 1
  vars:
    sca: "{{ hostvars[inventory_hostname]['sca'] }}"
    vault: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/vault.yml"
  tasks:
    - name: delete sca pipeline
      cloudformation:
        stack_name: "{{sca.aws.cf.pipeline.name}}"
        state: "absent"
        region: "{{awsRegion}}"
      delegate_to: localhost