- name: delete sca stack azure
  hosts: sca_azure
  gather_facts: false
  serial: 1
  vars:
    sca: "{{ hostvars[inventory_hostname]['sca'] }}"
    vault: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/vault.yml"
  tasks:
    - name: delete sca stack
      azure_rm_deployment:
        resource_group: "{{sca.name}}_rg"
        name: "{{sca.name}}"
        state: absent
      delegate_to: localhost