- name: create sca stack aws
  hosts: sca_aws
  gather_facts: false
  serial: 1
  vars:
    sca: "{{ hostvars[inventory_hostname]['sca'] }}"
    vault: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/vault.yml"
  tasks:
    - name: create sca stack
      cloudformation:
        stack_name: "{{sca.name}}"
        state: "present"
        region: "{{awsRegion}}"
        disable_rollback: true
        #template: "f5-sca-securitystack/aws-quickstart-scca-main-same-net.json"
        template_url: "{{sca.aws.cf.template.url}}"
        capabilities: ["CAPABILITY_AUTO_EXPAND","CAPABILITY_IAM"]
        template_parameters:
          licenseKey1: "{{sca.license.bigip1}}"
          licenseKey2: "{{sca.license.bigip2}}"
          licenseKey3: "{{sca.license.bigip3}}"
          licenseKey4: "{{sca.license.bigip4}}"
          pBaselineCompliance: "{{sca.compliance}}"
          pProject: "quickstart-f5-scca-security"
          pQuickstartS3BucketName: "{{sca.aws.s3.bucket.name}}"
          pQuickstartS3KeyPrefix: "{{sca.aws.s3.bucket.folder}}"
          pVdssVpcCidr: "{{sca.aws.vpc.vdss.cidr}}"
          pAppVpcCidr: "{{sca.aws.vpc.app.cidr}}"
          pFargateVpcCidr: "{{sca.aws.vpc.fargate.cidr}}"
          sshKey: "{{sca.aws.ec2.sshkeyname}}"
          instanceTypeExternalTier: "{{sca.aws.ec2.tier1Size}}"
          instanceTypeInternalTier: "{{sca.aws.ec2.tier2Size}}"
        tags:
          Stack: "ansible-sca-cloudformation"
      delegate_to: localhost